version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Mexico_City
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
